---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-foo
  labels:
    app: nginx-foo
spec:
  replicas: 1
  selector:
   matchLabels:
    app: nginx-foo
  template:
    metadata:
      labels:
        app: nginx-foo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

